// <auto-generated />
using System;
using EcoTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoTrack.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoTrack.Models.Leitura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlertaGerado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.ToTable("Leituras");
                });

            modelBuilder.Entity("EcoTrack.Models.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MetaConsumoMensal")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recursos", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EcoTrack.Models.Agua", b =>
                {
                    b.HasBaseType("EcoTrack.Models.Recurso");

                    b.Property<double>("Pressao")
                        .HasColumnType("float");

                    b.Property<int>("TipoUso")
                        .HasColumnType("int");

                    b.ToTable("Aguas", (string)null);
                });

            modelBuilder.Entity("EcoTrack.Models.Energia", b =>
                {
                    b.HasBaseType("EcoTrack.Models.Recurso");

                    b.Property<double>("FatorEmissaoCO2")
                        .HasColumnType("float");

                    b.Property<int>("Fonte")
                        .HasColumnType("int");

                    b.Property<int>("Voltagem")
                        .HasColumnType("int");

                    b.ToTable("Energias", (string)null);
                });

            modelBuilder.Entity("EcoTrack.Models.Residuo", b =>
                {
                    b.HasBaseType("EcoTrack.Models.Recurso");

                    b.Property<bool>("Reciclavel")
                        .HasColumnType("bit");

                    b.Property<string>("TipoMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Residuos", (string)null);
                });

            modelBuilder.Entity("EcoTrack.Models.Leitura", b =>
                {
                    b.HasOne("EcoTrack.Models.Recurso", "Recurso")
                        .WithMany("Leituras")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("EcoTrack.Models.Agua", b =>
                {
                    b.HasOne("EcoTrack.Models.Recurso", null)
                        .WithOne()
                        .HasForeignKey("EcoTrack.Models.Agua", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoTrack.Models.Energia", b =>
                {
                    b.HasOne("EcoTrack.Models.Recurso", null)
                        .WithOne()
                        .HasForeignKey("EcoTrack.Models.Energia", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoTrack.Models.Residuo", b =>
                {
                    b.HasOne("EcoTrack.Models.Recurso", null)
                        .WithOne()
                        .HasForeignKey("EcoTrack.Models.Residuo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoTrack.Models.Recurso", b =>
                {
                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
